[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
patcher-args = "-e 'Custom branding' -OcustomName=YT Music -OcustomIcon=mmt"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "crimera ReVanced"
excluded-patches = "'Dynamic color'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "both"
version = "20.21.27"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -OcustomIcon=mmt -e 'Change header' -Ocustom=Premium"

